# MPG Cars

### Introduction:



### Step 1. Import the necessary libraries

In [13]:
import numpy as np
import pandas as pd

### Step 2. Import the  datasets [cars1.csv](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv) and [cars2.csv](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv) from the folder

In [23]:
cars1=pd.read_csv('cars1.csv')
cars2=pd.read_csv('cars2.csv')
# print(df1)
# print(df2)
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick,NaN,NaN,NaN,NaN,NaN
194,22.5,6,232,90,3085,17.6,76,1,amc hornet,NaN,NaN,NaN,NaN,NaN
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette,NaN,NaN,NaN,NaN,NaN
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody,NaN,NaN,NaN,NaN,NaN
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit,NaN,NaN,NaN,NaN,NaN

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [32]:
print(cars1.columns.tolist())

['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model', 'origin', 'car']

### Step 4. It seems our first dataset has some unnamed blank columns, fix cars1

In [30]:
cars1.drop(columns=['Unnamed: 9' ,'Unnamed: 10','Unnamed: 11'],inplace=True)
# cars1.drop(columns=['Unnamed: 12', 'Unnamed: 13'], inplace=True)
# cars1.drop(columns=['mpg'],inplace = True)

# print(cars1.columns.tolist())

# # print(cars1)

In [ ]:
# cars1.iloc[:,:9]

In [33]:
# cars1.dropna(axis=1,inplace=True)
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [34]:
cars1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64
 2   displacement  198 non-null    int64
 3   horsepower    198 non-null    object
 4   weight        198 non-null    int64
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64
 7   origin        198 non-null    int64
 8   car           198 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 14.1+ KB

In [35]:
cars2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           200 non-null    float64
 1   cylinders     200 non-null    int64
 2   displacement  200 non-null    int64
 3   horsepower    200 non-null    object
 4   weight        200 non-null    int64
 5   acceleration  200 non-null    float64
 6   model         200 non-null    int64
 7   origin        200 non-null    int64
 8   car           200 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 14.2+ KB

### Step 6. concat cars1 and cars2 into a single DataFrame called cars

In [ ]:
def con(cars1,cars2):
    if sorted(cars1.columns)==sorted(cars2.columns):
        return pd.concat([cars1,cars2],axis=0).reset_index(drop=True)
    else:
        return pd.concat([cars1,cars2],axis=1).reset_index(drop=True)

In [ ]:
cars= con(cars1,cars2)
cars

### Step 7. There is a column missing, called owners. Create a random number Series from 1 to 5.

In [ ]:
owner =np.random.randint(1,6,cars.shape[0])
owner

### Step 8. Add the column owners to cars

In [ ]:
cars['Owners']=owner

In [ ]:
cars