# Filtering and Sorting Data

### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset *chipotle.tsv*

In [9]:
chipo = pd.read_table('chipotle.tsv')

In [10]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [11]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 3. Assign it to a variable called chipo.

In [12]:
chipo = pd.read_table('chipotle.tsv')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. How many products cost more than $10.00? 

Use `str` attribute to remove the $ sign and convert the column to proper numeric type data before filtering.

In [13]:
chipo['item_price']=chipo['item_price'].str.replace('$','').astype(float)

In [15]:
chipo[chipo['item_price']>10.0].shape[0]

1130

### Step 5. What is the price of each item? 

print a data frame with only two columns `item_name` and that column which contain each `item_price`

In [18]:
chipo['each_item_price']= chipo['item_price']/chipo['quantity']

### Step 6. Sort by the name of the item

In [19]:
chipo.sort_values[by='item_name']

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3523379740.py, line 1)

### Step 7. What was the quantity of the most expensive item ordered?

In [24]:
chipo[chipo['each_item_price']==chipo['each_item_price'].count()]

Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price, each_item_price]
Index: []

In [ ]:
chipo['item_price'].max()

In [ ]:
chipo['item_name'].describe()

In [ ]:
chipo['item_name'].value_counts()

In [ ]:
# chipo['item_name'].tolist()
chipo.groupby('item_name').count()

In [ ]:
chipo.info()

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [25]:
chipo[chipo['item_name']=='Veggie Salad Bowl']['quantity'].sum()

18

### Step 9. How many times people orderd more than one Canned Soda?

In [27]:
chipo[(chipo['quantity']>1)&(chipo['item_name']=='Canned Soda')].shape[0]

20

In [26]:
chipo[('item_name']=='Canned Soda') & (chipo['quantity']>1)]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (725176532.py, line 1)

# how much quantity people orders more than one Canned Sode?

In [29]:
chipo[(chipo['quantity']>1)&(chipo['item_name']=='Canned Soda')]['quantity'].sum()

42